[versions]
armeria = "1.34.1"
grpc-java = "1.74.0"
kotlin = "2.1.10"
kotlinx-coroutines = "1.10.1"
netty = "4.2.7.Final"
protobuf = "4.30.0"
retrofit2 = "2.12.0"
spring-boot = "3.5.9"
thrift = "0.22.0"

[libraries]
# plugins
dependency-management-plugin = { module = "io.spring.gradle:dependency-management-plugin", version = "1.1.7" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-spring-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }

# bom
armeria-bom = { module = "com.linecorp.armeria:armeria-bom", version.ref = "armeria" }
grpc-bom = { module = "io.grpc:grpc-bom", version.ref = "grpc-java" }
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
netty-bom = { module = "io.netty:netty-bom", version.ref = "netty" }
retrofit-bom = { module = "com.squareup.retrofit2:retrofit-bom", version.ref = "retrofit2" }

# libraries
findbugs-jsr305 = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
javax-annotatoin-api = { module = "javax.annotation:javax.annotation-api", version = "1.3.2" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
libthrift = { module = "org.apache.thrift:libthrift", version.ref = "thrift" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "1.7.36" }

[plugins]
com-google-protobuf = { id = "com.google.protobuf", version = "0.9.5" }
com-linecorp-thrift-gradle-plugin = { id = "com.linecorp.thrift-gradle-plugin", version = "0.6.1" }
